<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/Data-Analatics/blob/main/pandas_task_csv02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [9]:
data=pd.read_csv(r'/content/Coffee_sales_uncleaned.csv')
data

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10.0,card,thirty eight,Latte,Morning,Fri,Mar,5.0,3.0,01-03-2024,15:50.5
1,twelve,card,NaN,Hot Chocolate,Afternoon,Fri,Mar,5.0,3.0,01-03-2024,19:22.5
2,12.0,card,38.7,lattee,Afternoon,Fri,Mar,5.0,3.0,01-03-2024,20:18.1
3,NaN,card,28.9,Americano,Afternoon,Fri,Mar,5.0,3.0,2024/03/01,46:33.0
4,13.0,card,38.7,Latte,Afternoon,Fri,Mar,5.0,3.0,01-03-2024,8pm
...,...,...,...,...,...,...,...,...,...,...,...
3542,10.0,card,35.76,Cappuccino,Morning,Sun,Mar,7.0,3.0,23-03-2025,34:54.9
3543,14.0,card,35.76,Cocoa,Afternoon,Sun,Mar,7.0,3.0,23-03-2025,43:37.4
3544,14.0,card,35.76,Cocoa,NaN,NaN,Mar,7.0,3.0,23-03-2025,44:16.9
3545,15.0,card,25.96,Americano,Afternoon,Sun,Mar,7.0,3.0,23-03-2025,47:28.7
3546,18.0,card,35.76,Latte,Night,Sun,NaN,7.0,3.0,23-03-2025,NaN

In [19]:
(1) #Convert the hour_of_day column to integer type (handle strings like "twelve").
data["hour_of_day"] = df["hour_of_day"].replace("twelve", 12)
data["hour_of_day"] = pd.to_numeric(df["hour_of_day"], errors="coerce").astype("Int64")

In [20]:
(2)
data["money"] = df["money"].replace("thirty eight", 38)
data["money"] = pd.to_numeric(df["money"], errors="coerce")

In [15]:
(3)
data["Data"]=pd.to_datetime(df["Date"],errors="coerce")

In [13]:
(4)
data.shape

(3547, 11)

In [17]:
(5)
data_clean = df.dropna()
data_clean.shape

(797, 11)

In [21]:
(6)
data["new_column"] = 0
data.shape

(3547, 13)

In [22]:
(7) #describe()
data.describe()

,hour_of_day,money,Weekdaysort,Monthsort,Date,Data,new_column
count,3370.0,3370.000000,3370.000000,3370.000000,1337,1337,3547.0
mean,14.191988,31.656297,3.846291,6.440059,2024-10-09 18:34:44.068810752,2024-10-09 18:34:44.068810752,0.0
min,6.0,18.120000,1.000000,1.000000,2024-01-03 00:00:00,2024-01-03 00:00:00,0.0
25%,10.0,27.920000,2.000000,3.000000,2024-05-08 00:00:00,2024-05-08 00:00:00,0.0
50%,14.0,32.820000,4.000000,7.000000,2024-09-07 00:00:00,2024-09-07 00:00:00,0.0
75%,18.0,35.760000,6.000000,10.000000,2025-03-02 00:00:00,2025-03-02 00:00:00,0.0
max,22.0,38.700000,7.000000,12.000000,2025-12-03 00:00:00,2025-12-03 00:00:00,0.0
std,4.235596,4.880474,1.973284,3.497715,NaN,NaN,0.0

In [23]:
(8) #categorical ststistics
data.describe(include="object")

       cash_type          coffee_name Time_of_Day Weekday Month_name     Time
count       3370                 3371        3370    3370       3370     3370
unique         2                    9           3       7         12     3209
top         card  Americano with Milk   Afternoon     Tue        Mar  17:38.7
freq        3369                  761        1150     540        468        3

In [25]:
(9) #compare before and after cleaning
print("Before:")
print(df.describe())

print("After:")
print(data_clean.describe())

Before:
       hour_of_day        money  Weekdaysort    Monthsort  \
count       3370.0  3370.000000  3370.000000  3370.000000
mean     14.191988    31.656297     3.846291     6.440059
min            6.0    18.120000     1.000000     1.000000
25%           10.0    27.920000     2.000000     3.000000
50%           14.0    32.820000     4.000000     7.000000
75%           18.0    35.760000     6.000000    10.000000
max           22.0    38.700000     7.000000    12.000000
std       4.235596     4.880474     1.973284     3.497715

                                Date
count                           1337
mean   2024-10-09 18:34:44.068810752
min              2024-01-03 00:00:00
25%              2024-05-08 00:00:00
50%              2024-09-07 00:00:00
75%              2025-03-02 00:00:00
max              2025-12-03 00:00:00
std                              NaN
After:
       hour_of_day       money  Weekdaysort   Monthsort  \
count        797.0  797.000000   797.000000  797.000000
mean     14.100376   31.787478     3.849435    6.450439
min            7.0   18.120000     1.000000    1.000000
25%           10.0   27.920000     2.000000    3.000000
50%           14.0   32.820000     4.000000    7.000000
75%           18.0   35.760000     6.000000   10.000000
max           22.0   38.700000     7.000000   12.000000
std       4.248554    4.782142     2.042246    3.578497

                                Date
count                            797
mean   2024-10-11 11:42:50.138017536
min              2024-01-03 00:00:00
25%              2024-05-08 00:00:00
50%              2024-09-09 00:00:00
75%              2025-03-02 00:00:00
max              2025-12-03 00:00:00
std                              NaN

In [26]:
(10) #extract coffee_name as a series
coffee = df["coffee_name"]

print(type(coffee))

<class 'pandas.core.series.Series'>

In [27]:
(11) #count unique coffee names
df["coffee_name"].nunique()

9

In [28]:
(12) # first 10 weekday
df["Weekday"].head(10)

0    Fri
1    Fri
2    Fri
3    Fri
4    Fri
5    Fri
6    Fri
7    Fri
8    Fri
9    Fri
Name: Weekday, dtype: object

In [29]:
(13) #cash_type frequency
df["cash_type"].value_counts()

cash_type
card     3369
CARD        1
Name: count, dtype: int64

In [30]:
(13) # 'card','card'
print(df["cash_type"].unique())

['card' 'CARD ' nan]

In [31]:
df["cash_type"] = df["cash_type"].str.strip().str.lower()

print(df["cash_type"].value_counts())

cash_type
card    3370
Name: count, dtype: int64